# This configuration file tells Netlify how to handle your functions.
# Place this file in the root of your project folder.

[functions]
  # This sets the default directory for all serverless functions.
  directory = "netlify/functions"

# This increases the timeout for the sleeper function specifically.
[functions.sleeper]
  timeout = 25
